### ISSUE TITLE
feat(config): reject unknown config options outright

### ISSUE THREAD

**Issue by mmalenic** [umccr/htsget-rs#228]
The htsget-rs server should reject any unknown config options outright when parsing the config. Because the config can be quite complex, it's easy to mistakenly apply a config option that is unknown, where the server accepts the configuration file and just defaults any missing values. This leads to confusion when the server doesn't behave in the way that the user intended.

For example, say TLS is desired on the ticket server, the `cert` and `key` options may accidentally not be put under the `ticket_server_tls` table:

```toml
ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"
cert = "cert.pem"
key = "key.pem"
data_server_addr = "0.0.0.0:8081"
```

This results in a ticket server that performs no TLS, where the intended config would have been:

```toml
ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"
ticket_server_tls.cert = "cert.pem"
ticket_server_tls.key = "key.pem"
data_server_addr = "0.0.0.0:8081"
```
